spring:
  datasource:
    url: jdbc:mysql://localhost:3306/weather_db?useUnicode=yes&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update     # IMPORTANT it makes sure the connected database is the same as mapped in model package, if not it updates db to be as mapping requires(saying mapped i mean it reads @OneToMany ,@JoinTable and adjusts DB)
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
  quartz:
    job-store-type: memory
    properties:
      org:
        quartz:
          threadPool:
            threadCount: 5